### ISSUE TITLE
is cargo edit the correct way to install the project?

### ISSUE THREAD

**Issue by ashleygwilliams** [yoshuawuyts/github-templates#2]
## Question
In looking at how to run this project I was instructed to use `$ cargo add github-templates`. `add` is a command afforded to `cargo` via the `cargo-edit` package. `cargo add` adds the project to my `Cargo.toml`.

## Context
How has this issue affected you? What are you trying to accomplish?

Requiring a thirdparty tool to install the project with no explanation about that third party tool could be confusing. Additionally, I think this project should be installed as a CLI tool? If that's true, I'm not sure that `cargo add` is the correct instruction, even if `cargo-edit` is explained.

**Comment by yoshuawuyts** [comment]
Oh yeah, instead of `cargo add` it should be `cargo install` for the command line tool.
